
spring:
  codec:
    max-in-memory-size: 8MB
  main:
    banner-mode: off
  profiles:
    active: local
    group:
      local: fs,insecure
  application:
    name: graphql-playground

springdoc:
  api-docs:
    path: /internal/api-docs

application:
  version: ${DD_VERSION:local}

info: # exposed via /actuator/info
  version: ${application.version}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  info:
    env:
      enabled: true
    git:
      enabled: false

server:
  forward-headers-strategy: framework
  accesslog:
    enabled: true
    suppress:
      - /actuator
      - /webjars

