apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-helm-chart.fullname" . }}-xds
  labels:
    {{- include "springboot-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.discoveryService.port }}
      targetPort: {{ .Values.discoveryService.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "springboot-helm-chart.selectorLabels" . | nindent 4 }}
